Bug 1274201 - Fixing non-root installations if using a local connection
Previously we were writing out a inventory like this:

~~~
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
deployment_type=openshift-enterprise
ansible_connection=local

[masters]
ose3-master.example.com  openshift_hostname=ose3-master.example.com

[nodes]
ose3-master.example.com  openshift_hostname=ose3-master.example.com
ose3-node1.example.com  openshift_hostname=ose3-node1.example.com
ose3-node2.example.com  openshift_hostname=ose3-node2.example.com
~~~

The problem with that is now all the hosts are consider local connections.  In
addition our sudo check wasn't working as expected.  We would check that we
have sudo, but the playbooks were not running with root privileges.  When
gathering facts you'd hit:

~~~
__main__.OpenShiftFactsFileWriteError: Could not create fact file: /etc/ansible/facts.d/openshift.fact, error: [Errno 13] Permission denied: '/etc/ansible/facts.d/openshift.fact'
~~~

Instead the test for locale connections needs to be per host.  Anytime we're not running as root we need `ansible_become` set:

~~~
ose3-master.example.com  openshift_hostname=ose3-master.example.com ansible_connection=local ansible_become=true
~~~