docker_creds: fix python3 exception
Solves this exception with python3:

TypeError: a bytes-like object is required, not 'str

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>