Pin msgpack
Tests are failing with:
ERROR: Could not build wheels for msgpack which use PEP 517 and cannot be installed directly

Pin msgpack to 1.0.3, which is the last version I see in a successful
test.